name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GUM_OPTIONS: '--enable-gumpp --enable-gumjs --with-devkits=gum,gumjs --enable-tests'

jobs:
  gir:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
              gobject-introspection \
              libdwarf-dev \
              libelf-dev \
              libgirepository1.0-dev \
              libglib2.0-dev \
              libjson-glib-dev \
              libsoup-3.0-dev \
              libsqlite3-dev \
              libunwind-dev \
              ninja-build
      - name: Build
        run: |
          ./configure \
              --enable-shared \
              --without-prebuilds=toolchain,sdk \
              --disable-tests
          make
      - name: Upload GObject introspection data
        uses: actions/upload-artifact@v4
        with:
          name: gum-gir
          path: |
            build/gum/Gum-1.0.gir
            build/gum/Gum-1.0.typelib
   
  mobile:
    strategy:
      matrix:
        id:
          - android-arm
          - android-arm64
      fail-fast: false
    runs-on: ${{ startsWith(matrix.id, 'ios-') && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: nttld/setup-ndk@v1
        if: startsWith(matrix.id, 'android-')
        id: setup-ndk
        with:
          ndk-version: r25
          add-to-path: false
      - name: Set ANDROID_NDK_ROOT
        if: startsWith(matrix.id, 'android-')
        run: echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
      - name: Build
        run: |
          ./configure --host=${{ matrix.id }} ${{ env.GUM_OPTIONS }}
          make
      - name: Upload Gum devkit
        uses: actions/upload-artifact@v4
        with:
          name: gum-devkit-${{ matrix.id }}
          path: build/gum/devkit/
      - name: Upload GumJS devkit
        uses: actions/upload-artifact@v4
        with:
          name: gumjs-devkit-${{ matrix.id }}
          path: build/bindings/gumjs/devkit/
  
